name: Auto PR to dev

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  create-dev-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check if branch is hotfix
      id: check_branch
      run: |
        if [[ "${{ github.event.pull_request.head.ref }}" == hotfix* ]]; then
          echo "HOTFIX=true" >> $GITHUB_ENV
        else
          echo "HOTFIX=false" >> $GITHUB_ENV
        fi

    - name: Create PR to dev
      if: env.HOTFIX == 'true'
      env:
        PAT_TOKEN: ${{ secrets.DEV }}
      run: |
        PR_TITLE=$(curl -s -H "Authorization: token $DEV" https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r '.title')
        PR_BODY=$(curl -s -H "Authorization: token $DEV" https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r '.body')
        curl -s -X POST -H "Authorization: token $DEV" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/pulls -d "{\"title\":\"$PR_TITLE\",\"body\":\"$PR_BODY\",\"head\":\"${{ github.event.pull_request.head.ref }}\",\"base\":\"dev\"}"
